class Stats:

    CONFIG = "config"
    TRAFFIC = "traffic"
    GPL = "gpl"
    LATENCY = "latency"
    STATUSCODES = "status_codes"

    def __iter__(self):
        for v in [
                self.CONFIG,
                self.TRAFFIC,
                self.GPL,
                self.LATENCY,
                self.STATUSCODES]:
            yield v

class Values:

    def tag(stats):
        return [{"id": i, "name": n} for i, n in enumerate(stats, 1)]

    def list(name):
        return list(map(lambda i: i["name"], getattr(Values, name.upper())))

    TRAFFIC = tag([
        "cps",
        "rps",
        "rrps",
        "drps",
        "sps",
        "gos",
        "total",
        "success",
        "failed",
        "registration_total",
        "registration_success",
        "registration_gos",
        "registration_failed",
        "registration_retry",
        "registration_gos_excluding_retry",
        "registration_expiry",
        "subscribe_total",
        "subscribe_success",
        "subscribe_failed",
        "subscribe_gos",
        "call_gos",
        "call_total",
        "call_success",
        "call_failed",
        "call_retry",
        "call_cps",
        "conference_duration_min",
        "conference_duration_max",
        "deregistration_total",
        "deregistration_success",
        "deregistration_failed",
        "message_cps",
        "message_gos",
        "message_sent",
        "message_received",
        "message_success",
        "message_failed",
        "media_total",
        "media_success",
        "media_failed",
        "media_unknown",
        "media_dropped",
        "media_error",
        "media_packets_sent",
        "media_packets_received",
        "media_packets_lost",
        "media_packets_duplicated",
        "media_packets_late",
        "media_packets_reordered",
        "media_latency_95",
        "presence_load_time",
        "xcap_put_sent",
        "xcap_put_success",
        "xcap_put_failed",
        "xcap_put_timeout",
        "xcap_get_sent",
        "xcap_get_success",
        "xcap_get_failed",
        "xcap_get_timeout",
        "xcap_delete_sent",
        "xcap_delete_success",
        "xcap_delete_failed",
        "xcap_delete_timeout",
        "xcap_post_create_sent",
        "xcap_post_create_success",
        "xcap_post_create_failed",
        "xcap_post_create_timeout",
        "xcap_post_delete_sent",
        "xcap_post_delete_success",
        "xcap_post_delete_failed",
        "xcap_post_delete_timeout",
        "xcap_all_sent",
        "xcap_all_success",
        "xcap_all_failed",
        "xcap_all_timeout"])

    GROUPS = tag([
        "-",
        "registration",
        "call",
        "subscribe",
        "message",
        "xcap",
        "media",
        "sip"])

    GPL = tag([
        "rps",
        "registration_total",
        "registration_success",
        "registration_failed",
        "registration_retry",
        "registration_gos",
        "registration_gos_excluding_retry",
        "call_cps",
        "call_total",
        "call_success",
        "call_failed",
        "call_retry",
        "call_gos",
        "call_gos_excluding_retry",
        "subscribe_total",
        "subscribe_success",
        "subscribe_failed",
        "subscribe_gos",
        "message_cps",
        "message_sent",
        "message_received",
        "message_success",
        "message_failed",
        "message_retry",
        "message_gos",
        "xcap_all_gos",
        "xcap_all_sent",
        "xcap_all_success",
        "xcap_all_failed",
        "xcap_all_timeout",
        "xcap_put_gos",
        "xcap_put_sent",
        "xcap_put_success",
        "xcap_put_failed",
        "xcap_put_timeout",
        "xcap_get_gos",
        "xcap_get_sent",
        "xcap_get_success",
        "xcap_get_failed",
        "xcap_get_timeout",
        "xcap_delete_gos",
        "xcap_delete_sent",
        "xcap_delete_success",
        "xcap_delete_failed",
        "xcap_delete_timeout",
        "xcap_post_create_gos",
        "xcap_post_create_sent",
        "xcap_post_create_success",
        "xcap_post_create_failed",
        "xcap_post_create_timeout",
        "xcap_post_delete_gos",
        "xcap_post_delete_sent",
        "xcap_post_delete_success",
        "xcap_post_delete_failed",
        "xcap_post_delete_timeout",
        "media_total",
        "media_success",
        "media_failed",
        "media_unknown",
        "media_dropped",
        "media_error",
        "media_packets_sent",
        "media_packets_received",
        "media_packets_lost",
        "media_packets_duplicated",
        "media_packets_late",
        "media_packets_reordered",
        "media_latency_95",
        "sip_outgoing_bye",
        "sip_outgoing_retransmitted_bye",
        "sip_incoming_bye",
        "sip_outgoing_invite",
        "sip_outgoing_retransmitted_invite",
        "sip_incoming_invite",
        "sip_outgoing_register"])

    REQUEST = tag([
        "REGISTER(o)-401(i)-REGISTER(o)-200(i)",
        "INVITE(o)-180(i)",
        "INVITE(o)-200(i)",
        "INVITE(o)-183(i)",
        "INVITE(i)-180(o)",
        "INVITE(i)-183(o)",
        "BYE(o)-200(i)",
        "HANDOVER_INVITE(o)-200(i)"])

    CONFIG = tag([
        "cps",
        "rps",
        "call_answer_time_min",
        "call_holding_time_min",
        "call_duration",
        "rrps",
        "reregistration_margin",
        "user_count",
        "simultaneous_calls",
        "codec",
        "protocol"])

    METHOD = tag([
        "ACK",
        "BYE",
        "CANCEL",
        "INVITE",
        "MESSAGE",
        "NOTIFY",
        "PRACK",
        "REFER",
        "REGISTER",
        "SUBSCRIBE",
        "UPDATE"])
